<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main"/>
    <title>Profile services</title>
</head>

<body>
<h1>Profile services</h1>

<div id="controller-list" role="navigation">
    <p>Some services require an Access Token for the target collection. Access tokens can be generated by the Collection Administrator. These services are marked with an asterisk *. Services that do not require an Access Token cannot be used to retrieve data from private collections.</p>

    <h2>Available Public Services:</h2>
    <ul>
        <li>
            <b>Count all profiles in a collection</b> - /api/v1/opus/[opusId]/count[?includeArchived=false] - count all profiles in the collection (optionally include archived profiles - defaults to false)
        </li>
        <li>
            <b>* Export all profiles in a collection (results are paged)</b> - /api/v1/opus/[opusId]/export[?max=1000&offset=0&includeArchived=false&summary=false]
            <ul>
                <li>max - The maximum number of profiles to retrieve (profiles will be sorted alphabetically by name). Default = 500.</li>
                <li>offset - The 0-based index of the profile to start from (profiles will be sorted alphabetically by name). Default = 0.</li>
                <li>includeArchived - True to include archived profiles in the export. Default = false.</li>
                <li>summary - If true, only the profile name details, 'name' attributes and the 'summary' attribute will be included. If true, all data will be included. Default = false.</li>
            </ul>
        </li>
        <li>
            <b>Retrieve specific profiles from one or more public collections</b> - /api/v1/profiles?profileNames=...&guids=...&opusIds=...&summary=false
            <ul>
                <li>profileNames - comma-separated list of profile names to be exported. This can be used instead or as well as the guids parameter, but one or the other must be provided.</li>
                <li>guids - comma-separated list of name GUIDs to be exported. This can be used instead or as well as the profileNames parameter, but one or the other must be provided. The GUID is the ID of the ALA-matched Name for the profile (aka LSID).</li>
                <li>opusIds - comma-separated list of Collection IDs, short names, and or data resource uids to identify the collection(s) to be included in the export. If not provided, then all public collections will be used.</li>
                <li>tags - comma-separated list of Tags to identify the collection(s) to be included in the export. This can be used instead of, or as well as, opusIds.</li>
                <li>summary - If true, only the profile name details, 'name' attributes and the 'summary' attribute will be included. If true, all data will be included. Default = false.</li>
            </ul>
        </li>
    </ul>
</div>
</body>
</html>
