<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main"/>
    <title>Profile Services</title>
</head>
<body>
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="jumbotron">
                <h1>Profile Services</h1>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <h1>Public Services</h1>
            <div class="table-responsive">
                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th>Service</th>
                        <th>Requires Access Token?</th>
                        <th>Example</th>
                        <th>Notes</th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <td>Count all profiles in a collection</td>
                        <td>No</td>
                        <td>/api/v1/opus/[opusId]/count[?includeArchived=false]</td>
                        <td>Counts all profiles in the collection. Optionally include archived profiles using <code>includeArchived</code> (default: <code>false</code>)</td>
                    </tr>
                    <tr>
                        <td>Export all profiles in a collection (results are paged)</td>
                        <td>Yes</td>
                        <td>/api/v1/opus/[opusId]/export[?max=1000&amp;offset=0&amp;includeArchived=false&amp;summary=false]</td>
                        <td>
                            <dl>
                                <dt><code>max</code></dt>
                                <dd>The maximum number of profiles to retrieve (profiles will be sorted alphabetically by name). Default: <code>500</code>.</dd>
                                <dt><code>offset</code></dt>
                                <dd>The 0-based index of the profile to start from (profiles will be sorted alphabetically by name). Default: <code>0</code>.</dd>
                                <dt><code>includeArchived</code></dt>
                                <dd>Whether to include archived profiles in the export. Default: <code>false</code>.</dd>
                                <dt><code>summary</code></dt>
                                <dd>Whether to generate a summary of the included profiles. If <code>true</code>, only the profile name details, <code>name</code> attributes and the <code>summary</code> attribute will be included. If <code>false</code>, all data will be included. Default: <code>false</code>.</dd>
                            </dl>
                        </td>
                    </tr>
                    </tbody>
                </table>
            </div>
            <div class="alert alert-info">
                <p><strong>Some services require an Access Token for the target collection.</strong></p>
                <p>Access tokens can be generated by the Collection Administrator. Services that do not require an Access Token cannot be used to retrieve data from private collections.</p>
            </div>
        </div>
        <div class="col-md-12">
            <h1>Admin Tools</h1>
            <g:form url="admin/search/reindex" method="post"><g:submitButton class="btn btn-warning" name="Reindex"/></g:form>
            <g:form uri="admin/names/clearCache" method="post"><g:submitButton class="btn btn-warning" name="Clear NSL Name Dump cache"/></g:form>
        </div>
    </div>
</div>
</body>
</html>
